version: "3.2"
services:
  apiserver:
    build: ./ADAPT-2_Server
    volumes:
      -  /mnt/d10/assda/publish/ANU/adapt2-test-archive:/server/data 
    ports:
      - "3061:3060"
    network_mode: host
    container_name: apiserver
